baseURL = 'https://sijeni.li.pona.la/'
title = 'sieni'
disableKinds = ["taxonomy", "term"]

[permalinks]
  tp = "/tp/:contentbasename"
  sp = "/sp/:contentbasename"
  eo = "/eo/:contentbasename"
  es = "/es/:contentbasename"

[outputs]
  home = ["HTML"]

[markup.goldmark.renderer]
  unsafe = true
[markup.goldmark.parser]
  autoHeadingID = false
[markup.goldmark.parser.attribute]
  block = true
  title = true

[caches.images]
  dir = ':cacheDir/images'

[outputFormats.RSS]
  baseName = "rss"
